[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "genomic_benchmark"
version = "0.1.0"
description = "Benchmark for DNA sequence-based model"
requires-python = ">=3.7"

[tool.hatch.build.targets.wheel]
packages = ["src"] 